### ISSUE TITLE
Python async API

### ISSUE THREAD

**Issue by dimddev** [Tinkerforge/master-brick#2]
Hello there,

do you have a plan, the Python API to be rewritten from blocking to non-blocking, 

for example I have using Twisted to control my bricks and bricklets, 

and I have to rewrite the used method to be async with defer, it's not hard for me, 

but will be nice if the python API have this futures

**Comment by photron** [comment]
Sorry, we don't plan to add non-blocking behavior.

**Comment by dimddev** [comment]
Okay thank you.
